version: '3'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9-adri
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - bind_config:/etc/bind
      - bind_cache:/var/cache/bind
      - bind_lib:/var/lib/bind
    restart: unless-stopped

volumes:
  bind_config:
  bind_cache:
  bind_lib:
